language: php

services:
  - docker

php:
  - '7.2'

git:
  depth: 1

before_install:
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - pecl channel-update pecl.php.net
  - yes "" | pecl install yaml
  - composer install
  - vendor/unb-libraries/dockworker/scripts/travis/init.sh

script:
  - set -e
  - vendor/bin/dockworker local:build-test
  - vendor/unb-libraries/dockworker/scripts/kubectl/init.sh
  - vendor/bin/dockworker image:deploy $TRAVIS_BRANCH
  - vendor/bin/dockworker deployment:logs:check $TRAVIS_BRANCH

notifications:
  slack:
    rooms:
      secure: UHtO6WiAcFSMH3+e6A+iHorcYZaW03YhJVQs84HUp/cVI7eahMoNDYydEyeM/PRLHtRVx9ED6Ibu7A6nHV1n8nVFO0GS58jXaDHosfKXqFsUdcyQb/xsFTw3Kmm24G3XNjsu5BPrG7GVtrjPRf97LFRNMb9gVTJ4rZ9HIEGloUBIUnehoBPqJ3aBF10tM8o9zm3JmaFciqIVNvzmDfrH4xt2YpXySvgeJE9NTHvM6/pvbGiVc4jjMizDT6rNCTVBYOfAFNqYcDkvP7uNaNqp27tP/FG0qwGFdpJ+SX4RLG/f4ehoT0lVMyJoXW2Uy2F7ZjVY2xLI7Im+p/wwMYrauaFQkAZzZq5TKCurB7D/aeddO0MWGZyUucEZyNrNlx43OTLMbATg9WZ/p6Ac1dcMAQ59pK5t93lKy+fSgd8UfqPg+AMuV5Iq2UUPgsQsKV02PwF1LOvDU7AcasDU+kDsq4thBtcqmza30UQ5/eN7SJlYorUrCUvpzYUo3NMgam4YzYC3tpw7pk/iIol6Ax3PUbE+0gbV9iUXy6fHpt4LEJidYEpvOLyODVbdEvIyIq2nnQTFh/BVT+lWcG5qJlDX2lVFBT1CdvtcUBfx+locab+3zRKT0AKDWUXLIwZfyMMuoAX+nFj6H4gWt2OgblUqj+XYk6sEoUtZC6iYgsncREQ=
    on_start: always
    on_success: always
