<?php

/**
 * @file
 * Contains bnald_migrate.module.
 */

use Drupal\migrate\Plugin\MigrationInterface;
use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Row;

/**
 * Implements hook_migrate_MIGRATION_ID_prepare_row().
 *
 * Grant permission to view published legislation before migrating
 * the anonymous user role.
 */
function bnald_migrate_migrate_d7_user_role_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  $role_name = $row->getSourceProperty('name');
  if ($role_name === 'anonymous user') {
    $permission_to_grant = 'view published legislation entities';
    $permissions = $row->getSourceProperty('permissions');
    if (!in_array($permission_to_grant, $permissions)) {
      $permissions[] = $permission_to_grant;
    }
    $row->setSourceProperty('permissions', $permissions);
  }
}
