<?php

/**
 * @file
 * Contains bnald_migrate.module.
 */

use Drupal\migrate\Plugin\MigrationInterface;
use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Row;
use Drupal\migrate\MigrateSkipRowException;

/**
 * Implements hook_migrate_MIGRATION_ID_prepare_row().
 */
function bnald_migrate_migrate_user_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  $username = $row->getSourceProperty('name');
  if ($username === 'admin') {
    throw new MigrateSkipRowException('The user admin already exists. Row ignored.');
  }
}
