<?php

/**
 * @file
 * Contains einbaum.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Component\Utility\NestedArray;

/**
 * Implements hook_theme().
 */
function einbaum_theme($existing, $type, $theme, $path) {
  return [
    'page_title' => [
      'render element' => 'elements',
    ],
    'status_messages' => [
      'render element' => 'elements',
    ],
  ];
}

function template_preprocess_page_title(array &$variables) {
  $variables['title_attributes']['data-test'] = 'page-title';
}

function template_preprocess_status_messages(array &$variables) {
  $test_id = implode('-', array_keys($variables['message_list']));
  $variables['attributes']['data-test'] = $test_id;
}

/**
 * Implements hook_form_alter().
 */
function einbaum_form_alter(array &$form, FormStateInterface $form_state, string $form_id) {
  if ($form['actions']['submit']) {
    $form['actions']['submit']['#attributes']['data-test'] = 'submit';
  }
}

/**
 * Implements hook_field_widget_complete_WIDGET_TYPE_form_alter().
 */
function einbaum_field_widget_complete_form_alter(&$field_widget_complete_form, FormStateInterface $form_state, $context) {
  /** @var \Drupal\Core\Field\FieldItemListInterface $items */
  $items = $context['items'];

  /** @var \Drupal\Core\Field\WidgetInterface $widget */
  $widget = $context['widget'];

  $field_storage_definition = $items
    ->getFieldDefinition()
    ->getFieldStorageDefinition();

  $main_property = $field_storage_definition->getMainPropertyName();
  $properties = $field_storage_definition->getPropertyNames();
  $test_id = $items
    ->getFieldDefinition()
    ->getName();

  foreach ($properties as $property) {
    switch ($widget->getPluginId()) {
      case 'entity_reference_autocomplete_tags':
        $key = ['widget', $property];
        break;
      case 'file_generic':
        $key = FALSE;
        break;
      default:
        $key = ['widget', 0, $property];
        if (array_key_exists('delta', $context)) {
          array_splice($key, 1, 1, $context['delta']);
        }
    }

    if ($key) {
      array_push($key, '#attributes', 'data-test');
      NestedArray::setValue($field_widget_complete_form, $key, $property === $main_property
        ? $test_id
        : "{$test_id}__{$property}"
      );
    }
  }
}

/**
 * Implements hook_element_info_alter().
 */
function einbaum_element_info_alter(array &$info) {
  $info['managed_file']['#process'][] = 'einbaum_managed_file_process';
}

/**
 * Additional #process callback for "managed_file" form elements.
 *
 * @param array $element
 *   The element's render array.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The current state of the form.
 * @param array $complete_form
 *   The render array of the form the element is part of.
 *
 * @return array
 *   A modified element render array.
 */
function einbaum_managed_file_process(array &$element, FormStateInterface $form_state, array &$complete_form) {
  $element['upload']['#attributes']['data-test'] = $element['#field_name'];
  return $element;
}
