<?php

/**
 * @file
 * Contains bnald_core.module.
 */

include_once 'bnald_core.legislation.chapter_sort.inc';

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\bnald_core\Entity\LegislationInterface;

/**
 * Implements hook_help().
 */
function bnald_core_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bnald_core module.
    case 'help.page.bnald_core':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Core functionality for BNALD, such as Entity Types') . '</p>';
      return $output;

    default:
  }
}

/**
 * Compute chapter_sort value to sort chapters in a natural order.
 *
 * Implements hook_ENTITY_TYPE_presave().
 */
function bnald_core_legislation_presave(LegislationInterface $legislation) {
  $chapter_sort = to_natural_sort_key($legislation->getChapter(), 5);
  $legislation->setChapterSort(str_replace(' ', '', $chapter_sort));
}

/**
 * Implements hook_link_alter().
 */
function bnald_core_link_alter(&$variables) {
  $url = $variables['url'];
  if (!$url->isRouted()) {
    return;
  }

  $route_name = $url->getRouteName();
  switch ($route_name) {
    case 'user.login':
      $variables['text'] = t('@text', [
        '@text' => 'Admin Login'
      ]);
      break;

    default:
      return;
  }
}

/**
 * Implements hook_theme().
 */
function bnald_core_theme($existing, $type, $theme, $path) {
  return [
    'legislation' => [
      'render element' => 'elements',
      'file' => 'legislation.page.inc',
    ],
  ];
}
