favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://local-bnald.lib.unb.ca:3099/themes/contrib/bootstrap/favicon.ico'
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: false
logo:
  path: ''
  url: ''
  use_default: true
schemas:
  bootstrap: 8000
  bnald_lib_unb_ca: 8000
